services:
  appserver:
    image: 'devwithlando/php:8.1-apache-4'
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
      COMPOSER_MEMORY_LIMIT: '-1'
      PHP_MEMORY_LIMIT: 1G
      PATH: >-
        /app/vendor/bin:/app/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/www/.composer/vendor/bin:/helpers
      LANDO_WEBROOT: /app/web
      XDEBUG_CONFIG: >-
        client_host=172.26.88.114 discover_client_host=1 log=/tmp/xdebug.log
        remote_enable=true remote_host=172.26.88.114
      XDEBUG_MODE: 'off'
    networks:
      default: {}
    ports:
      - '127.0.0.1::80'
    volumes:
      - /usr/local/bin
      - >-
        /home/tars/.lando/config/php/default-ssl.conf:/etc/apache2/sites-enabled/000-default.conf
      - >-
        /home/tars/.lando/config/php/php.ini:/usr/local/etc/php/conf.d/xxx-lando-default.ini
    command: docker-php-entrypoint sh -c 'a2enmod rewrite && apache2-foreground'
version: '3.6'
